### ISSUE TITLE
Feature: Allow controlled "Field.props.type"

### ISSUE THREAD

**Issue by Vidlec** [kettanaito/react-advanced-form#136] opened 2018-01-03 13:14 UTC
It is paramount that type is controlable. This will enable changing appearance of input, for example if you want to change from `password` to `text`

**Comment by kettanaito** [comment] 2018-01-03 15:12
This is a good improvement.

Please wait until I merge new field composition, since controlled type will most likely require some forced updates of the field, or similar handlers to call updateField when the type changes. Alternatively, this logic may be written in Field.componentWillReceiveProps.

Thanks.

**Comment by kettanaito** [comment] 2018-01-08 14:29
@Vidlec, hi.

Have you had any drafts for this change? Especially interesting in the light of field composition changes. Thanks.

**Comment by kettanaito** [comment] 2018-01-24 11:39
Making the `type` or any other prop controllable is not a problem.

The problem is how to make `contextProps` to listen to the changes of props which are important to `contextProps` (that includes `type`, `disabled`, `required`, etc.). This can also relate to #24, as the core concept of live updates is similar.

**Comment by kettanaito** [comment] 2018-01-29 11:25
Started the PoC of this change under [`dev/controlled-type`](https://github.com/kettanaito/react-advanced-form/tree/dev/controlled-type).

**Comment by kettanaito** [comment] 2018-02-12 16:45
Can be covered after RxProps introduction in #24.

**Comment by kettanaito** [comment] 2018-02-14 08:55
This issue is going to be covered by reactive props subscription in #24.

In fact, I have used this scenario (controlled `type`) to test the PoC of the reactive props and it went gracefully. Moreover, I have discovered that the `type` prop in the field's record is potentially redudndant, as it can be grabbed from `fieldProps.ref.props.type` and omit any synchronization between the record and the props.

I'm locking this issue for now to **prevent from any investigation* on this matter.

**Comment by Vidlec** [comment] 2018-02-28 12:58
Can be closed

**Comment by kettanaito** [comment] 2018-02-28 13:03
Solved by introducing the [Reactive props](https://github.com/kettanaito/react-advanced-form/issues/24).

Merged and published under [`0.20.0`](https://github.com/kettanaito/react-advanced-form/commit/8d5832ab70c4bb1a3f337262dfbc17947aa76302). Closing.

**Closed by kettanaito** 2018-02-28 13:03 UTC
Labels: improvement, possibly obsolete
